name: Style
on:
  push:
  pull_request:

jobs:
  style:
    if: >-
      github.repository_owner != 'Jackenmen'
      || github.event_name != 'push'
      || github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set up .NET CLI
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Add dotnet format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Install dependencies
        run: dotnet restore

      - name: Run build with warnings as errors
        run: dotnet build --no-restore /warnaserror

      - name: Run dotnet format
        run: dotnet format --verify-no-changes --verbosity diagnostic
        if: always()
