name: Test
on:
  push:
  pull_request:

jobs:
  test:
    if: >-
      github.repository_owner != 'Jackenmen'
      || github.event_name != 'push'
      || github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Set up .NET CLI
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore
